/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Corrida;

public class App {

    public static void main(String[] args) {
           App aplicacao = new App();
           Pessoa p1 = new Pessoa("Zezinho");
           Piloto pil = new Piloto("Huguinho");
    }
}
